[package]
name = "vendor-deps"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
libc = "0.2.0"
nom  = "1.2.3"

[dependencies.flavors]
git = "https://github.com/Geal/flavors"

[build-dependencies]
gcc = "^0.3"

